import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ENG' | 'தமிழ்';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  ENG: {
    // Hero Section
    'hero.title1': 'Our Lady Of Sorrows',
    'hero.title2': 'Martyr St. Devasahayam Shrine',
    'hero.subtitle': 'A Sacred Place of Prayer and Pilgrimage',
    
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.massBooking': 'Mass Booking',
    'nav.donations': 'Donations',
    'nav.gallery': 'Gallery',
    'nav.livestream': 'Live Stream',
    'nav.testimonies': 'Testimonies',
    'nav.prayerRequest': 'Prayer Request',
    'nav.contact': 'Contact',
    
    // Buttons
    'button.bookMass': 'Book a Mass',
    'button.donate': 'Make a Donation',
    'button.prayerRequest': 'Prayer Request',
    'button.learnMore': 'Learn More',
    'button.viewMore': 'View More...',
    
    // About Section
    'about.title': 'About Saint Devasahayam',
    'about.description': 'Welcome to Devasahayam Mount Shrine, a blessed sanctuary dedicated to Saint Devasahayam Pillai, the first Indian layman to be canonized by the Catholic Church.',
    
    // Management Section
    'management.title': 'Management',
    
    // Announcements Section
    'announcements.title': 'Important Announcements',
    'announcements.feast.title': 'Annual Feast Day Celebration',
    'announcements.feast.content': 'Join us for the grand celebration of Saint Devasahayam Feast Day on January 14, 2025. Special masses throughout the day.',
    
    // Call to Action Cards
    'cta.bookMass.title': 'Book a Mass',
    'cta.bookMass.description': 'Book a holy mass for your intentions and your loved ones',
    'cta.donation.title': 'Make a Donation',
    'cta.donation.description': 'Support the shrine and its charitable works',
    'cta.prayer.title': 'Prayer Request',
    'cta.prayer.description': 'Submit your prayer request to be remembered in our prayers',
    
    // Common
    'common.language': 'Language',
    'common.welcome': 'Welcome to our spiritual home',
    
    // About Page
    'about.page.title': 'Saint Devasahayam Pillai',
    'about.page.subtitle': 'India\'s First Lay Saint | Martyr of Faith | 1712 - 1752',
    'about.statue.title': 'Statue of Saint Devasahayam Pillai',
    'about.life.title': 'A Life of Faith & Courage',
    'about.life.description': 'Born as Neelakanta Pillai into an affluent Hindu Nair family in 1712, Devasahayam Pillai became the first Indian layman to be canonized as a saint by Pope Francis on May 15, 2022.',
    'about.journey.description': 'His journey from a palace official to a Christian martyr stands as a testament to unwavering faith and dignity in the face of persecution.',
    'about.early.title': 'Early Life & Conversion',
    'about.early.birth': 'Neelakandan Pillai was born on April 23, 1712, in Nattalam, Travancore.',
    'about.early.father': 'His father, Vasudevan Namboodiri, was a priest at the Adikesava Perumal Temple in Thiruvattar.',
    'about.early.palace': 'Growing up in an influential family with connections to the royal palace of Maharaja Marthanda Varma, Neelakandan entered palace service and rose to become an official under Ramayyan Dalawa.',
    'about.turning.title': 'The Turning Point',
    'about.turning.battle': 'In 1741, after the Battle of Colachel, Dutch commander Captain Eustachius De Lannoy was captured.',
    'about.turning.friendship': 'Through friendship with De Lannoy, Neelakandan became interested in Christianity.',
    'about.turning.baptism': 'In 1745, he was baptized as "Lazarus" and took the Malayalam name "Devasahayam," meaning "Help of God."',
    'about.timeline.title': 'Timeline of His Life',
    'about.timeline.date.birth': 'April 23, 1712',
    'about.timeline.date.battle': '1741',
    'about.timeline.date.conversion': '1745',
    'about.timeline.date.imprisonment': '1749 – 1752',
    'about.timeline.date.martyrdom': 'January 14, 1752',
    'about.timeline.date.beatified': 'December 2, 2012',
    'about.timeline.date.canonized': 'May 15, 2022',
    'about.timeline.birth': 'Born as Neelakanta Pillai in Nattalam, Travancore',
    'about.timeline.battle': 'Battle of Colachel – friendship with De Lannoy',
    'about.timeline.conversion': 'Converted to Christianity, baptized as Devasahayam',
    'about.timeline.imprisonment': 'Imprisoned and tortured for three years',
    'about.timeline.martyrdom': 'Martyred at Aralvaimozhy',
    'about.timeline.beatified': 'Beatified by Pope Benedict XVI',
    'about.timeline.canonized': 'Canonized by Pope Francis',
    'about.persecution.title': 'Persecution & Martyrdom',
    'about.persecution.anger': 'His conversion angered Brahmin priests and royal elites.',
    'about.persecution.accused': 'He was falsely accused, imprisoned, tortured, and publicly humiliated.',
    'about.persecution.faith': 'Despite suffering, his faith never wavered.',
    'about.miracle.quote': '"His witness to Christ is an example of that attentiveness to the coming of Christ. May this holy season help us to centre our lives once more on Christ, our hope."',
    'about.quote.attribution': '- Pope Benedict XVI, December 2, 2012',
    'about.persecution.conversion': 'Devasahayam\'s conversion to Christianity sparked outrage among the Brahmin priests, feudal lords, and members of the royal household. Leaving Hinduism was considered a grave offense, especially for someone of high Nair caste. False charges were brought against him, resulting in his imprisonment for three years.',
    'about.persecution.captivity': 'During his captivity, European powers lobbied for his release. Orders were eventually given for him to be exiled. However, the original order was altered, and instead of deportation to Dutch territory, he was taken to Aralvaimozhy border and subjected to brutal torture.',
    'about.persecution.torture': 'His body was painted with red and black spots, and he was forced to sit backward on a water buffalo - a symbol of death in Hindu tradition. Daily, he received eighty stripes, had pepper rubbed into his wounds, and was given only stagnant water to drink.',
    'about.tomb.cathedral': 'Saint Devasahayam Pillai\'s tomb in St. Francis Xavier\'s Cathedral at Kottar, Nagercoil, has become a major pilgrimage site. His body was recovered by local people after his martyrdom and carried to this church, where his mortal remains were interred near the altar.',
    'about.tomb.restoration': 'The tomb was restored and beautified after his beatification in 2012. Thousands of devotees visit annually to offer prayers and seek his intercession. His belongings are preserved in a church in Vadakkankulam, exposed every August 15th, the feast of the Assumption of Mary.',
    'about.pilgrimage.sites': 'Key pilgrimage sites include Puliyoorkurichi, where water miraculously gushed from a rock, and Aralvaimozhy, the site of his martyrdom where a church now stands commemorating his sacrifice.',
    'about.image.memorial': 'Memorial of Devasahayam Pillai',
    'about.image.memorial2': 'Devasahayam Pillai Memorial',
    'about.image.church': 'Church at the site of martyrdom',
    'about.sacred.title': 'Sacred Places & Final Resting Place',
    'about.sacred.tomb': 'His tomb at St. Francis Xavier\'s Cathedral, Kottar, is a major pilgrimage site.',
    'about.sacred.visitors': 'Thousands visit annually seeking his intercession.',
    'about.journey.sainthood': 'Journey to Sainthood',
    'about.journey.path': 'The path to canonization spanned over 270 years. His martyrdom was reported to the Vatican as early as 1756. In 1780, a petition for canonization was submitted. However, it wasn\'t until 1984 that serious efforts resumed through the initiative of lay persons from the Diocese of Kottar.',
    'about.journey.beatification': 'In 2012, Pope Benedict XVI recognized him as "Venerable" and on December 2, 2012, he was beatified in Nagercoil. Over 100,000 Catholics attended the ceremony. Finally, on February 21, 2020, Pope Francis recognized a miracle attributed to Devasahayam\'s intercession, clearing the way for his canonization on May 15, 2022.',
    'about.journey.process': 'The process took over 270 years.',
    'about.journey.completion': 'Canonization was completed on May 15, 2022.',
    'about.historic.achievement': 'Historic Achievement:',
    'about.historic.description': 'Saint Devasahayam Pillai is the first Catholic in India who is neither an ordained minister nor a religious to be officially recognized as a saint. His feast day is celebrated on January 14th.',
    'about.patron.saint': 'He is venerated as the patron saint of India and persecuted Christians worldwide. His life symbolizes the courage to follow one\'s conscience and faith despite social pressures and persecution. His story inspires believers to stand firm in their convictions while maintaining dignity and compassion.',
    'about.witness.legacy': 'Since the days of the interment of his mortal remains, many Christian pilgrims have visited his tomb and offered prayers. His witness to Christ continues to inspire millions, demonstrating that attentiveness to faith and courage in the face of adversity can leave a lasting legacy for generations.',
    'about.legacy.title': 'Legacy & Veneration',
    'about.legacy.symbol': 'Saint Devasahayam Pillai is venerated as a symbol of courage and faith.',
    'about.legacy.feast': 'His feast day is celebrated on January 14.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To inspire faith, hope, and love through the life of Saint Devasahayam.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To provide spiritual growth, worship, and service to the community.',
    'about.shrine.title': 'About Our Shrine',
    'about.shrine.description': 'The Devasahayam Mount Shrine honors the legacy of Saint Devasahayam Pillai.',
    'about.shrine.pilgrimage': 'The Devasahayam Pillai Shrine at Aralvaimozhi, Tamil Nadu, is a significant Christian pilgrimage site dedicated to Saint Devasahayam Pillai, India\'s first lay Catholic saint. Located near the historic Aralvaimozhi Pass, the shrine marks the place associated with his martyrdom and bears witness to his unwavering faith and sacrifice. Drawing devotees throughout the year, especially during the annual feast, the shrine stands as a symbol of courage, devotion, and spiritual inspiration for people of all faiths.',
    'about.services.title': 'Our Services & Activities',
    'about.services.masses': 'Daily Masses',
    'about.services.masses.time': 'Morning 6:00, 9:00, Evening 6:00',
    'about.services.pilgrimage': 'Pilgrimage Programs',
    'about.services.pilgrimage.desc': 'Pilgrimage and spiritual camps',
    'about.services.charity': 'Charitable Works',
    'about.services.charity.desc': 'Education, medical care, assistance for the poor',
    'about.services.confession': 'Confession & Counseling',
    'about.services.confession.desc': 'Sacrament of reconciliation and spiritual counseling',
    'about.services.feast': 'Feast Day Celebrations',
    'about.services.feast.desc': 'January 14 – Grand celebration',
    'about.services.youth': 'Youth Ministry',
    'about.services.youth.desc': 'Faith and community service programs for youth',
    
    // Mass Booking Page
    'mass.booking.title': 'Book a Holy Mass',
    'mass.booking.subtitle': 'Offer a Holy Mass for your intentions, loved ones, or in memory of departed souls. Please fill out the form below to submit your mass booking request.',
    'mass.booking.details': 'Booking Details',
    'mass.booking.fullName': 'Full Name',
    'mass.booking.email': 'Email Address',
    'mass.booking.phone': 'Phone Number',
    'mass.booking.date': 'Preferred Date',
    'mass.booking.time': 'Preferred Time',
    'mass.booking.intentionType': 'Mass Intention Type',
    'mass.booking.intentionDetails': 'Mass Intention Details',
    'mass.booking.numberOfDays': 'Number of Days',
    'mass.booking.numberOfDaysDesc': 'Book the same mass intention for multiple consecutive days starting from your selected date.',
    'mass.booking.submit': 'Submit Booking Request',
    'mass.booking.amount': 'Mass Booking Amount',
    'mass.booking.pricePerMass': 'Price per mass: ₹150',
    'mass.booking.paymentInstructions': 'Payment instructions will be sent after approval',
    'mass.booking.importantNotes': 'Important Notes',
    'mass.booking.note1': '• Bookings are subject to availability',
    'mass.booking.note2': '• You will receive confirmation via email',
    'mass.booking.note3': '• Please arrive 15 minutes before mass time',
    'mass.booking.note4': '• Contact us for special arrangements',
    'mass.booking.thanksgiving': 'Thanksgiving',
    'mass.booking.petition': 'Petition',
    'mass.booking.memorial': 'Memorial',
    'mass.booking.placeholder.thanksgiving': 'Enter thanksgiving intention details',
    'mass.booking.placeholder.petition': 'Enter petition request details',
    'mass.booking.placeholder.memorial': 'Enter memorial details (name of the person, etc.)',
    'mass.booking.placeholder.default': 'Enter mass intention details',
    'mass.timings.title': 'Mass Timings',
    'mass.timings.daily': 'Daily Mass',
    'mass.timings.monday.thursday': 'Monday - Thursday',
    'mass.timings.morning': 'Morning: 6:00 AM',
    'mass.timings.evening': 'Evening: 6:30 PM',
    'mass.timings.friday': 'Friday Mass',
    'mass.timings.friday.morning1': 'Morning: 6:00 AM Mass',
    'mass.timings.friday.morning2': 'Morning: 10:30 AM Novena Mass',
    'mass.timings.friday.morning3': 'Morning: 11:00 AM Novena Mass',
    'mass.timings.friday.evening': 'Evening: 6:30 PM Mass',
    'mass.timings.friday.night': 'Night: 8:00 PM Mass 9:00 PM',
    'mass.timings.saturday': 'Saturday Mass',
    'mass.timings.saturday.morning1': 'Morning: 6:00 AM Mass',
    'mass.timings.saturday.morning2': 'Morning: 11:30 AM Novena Mass',
    'mass.timings.saturday.evening': 'Evening: 6:30 PM Mass',
    'mass.timings.saturday.night': 'Night: 8:00 PM Mass 9:00 PM',
    'mass.timings.sunday': 'Sunday Mass',
    'mass.timings.sunday.morning1': 'Morning: 7:00 AM Mass',
    'mass.timings.sunday.morning2': 'Morning: 7:00 AM Mass',
    'mass.timings.sunday.afternoon': 'Afternoon: 12:00 PM (for Sacred Pilgrim)',
    'mass.timings.sunday.evening': 'Evening: 6:30 PM Mass',
    'mass.timings.sunday.night': 'Night: 8:00 PM Mass 9:00 PM',
    'mass.timings.novena1': '• Novena Devasahayam Anukunj',
    'mass.timings.novena2': '• Thiruvassal Vanakkam',
    'mass.timings.novena3': '• Thirugnanasambandar Vanakkam',
    'mass.timings.special': 'Special Days',
    'mass.timings.special.desc': 'Special Days are held at the Shrine on various dates each month, ensuring all visitors have the opportunity to participate.',
    'mass.timings.special.15th': '• On the 15th of every month - Patron Mass at 7:00 PM',
    'mass.timings.special.14th': '• On the 14th of every month - Matha Mahima - Evening Mass at 6:00',
    'mass.timings.special.tuesday': '• First Tuesday - St Anthony\'s Service',
    'mass.timings.special.wednesday': '• First Wednesday - Our Church',
    'mass.timings.special.friday': '• First Friday - Jesus Square',
    'mass.timings.special.saturday1': '• First Saturday - Devasahayam Patron',
    'mass.timings.special.saturday2': '• First Saturday - Mass at 7:00pm for Our Lady of Sorrows Blessed by Pope on Procession',
    
    // Payment Confirmation
    'payment.confirmation.required': 'Payment Confirmation Required',
    'payment.utr.number': 'Enter 12-digit UTR Number',
    'payment.utr.description': 'You can find this number in your payment app\'s transaction history',
    'payment.screenshot.upload': 'Upload Screenshot',
    'payment.screenshot.click': 'Click to upload screenshot',
    'payment.screenshot.format': 'PNG, JPG formats – Maximum 5MB',
    'payment.submit.details': 'Submit Payment Details',
    'payment.summary': 'Payment Summary',
    'payment.complete': 'Complete Your Payment',
    'payment.qr.scan': 'Scan QR Code to Pay',
    'payment.qr.description': 'Scan with any UPI app (Google Pay, PhonePe, Paytm, etc.)',
    'payment.amount': 'Amount',
    'payment.made': 'I\'ve Made the Payment',
    'payment.utr.label': 'UTR Number / Transaction ID',
    'payment.utr.placeholder': 'Enter 12-digit UTR number',
    'payment.utr.help': 'Find this in your payment app\'s transaction history',
    'payment.screenshot.label': 'Payment Screenshot',
    'payment.screenshot.formats': 'PNG, JPG up to 5MB',
    'payment.submitting': 'Submitting...',
    'payment.success.title': 'Payment Details Submitted',
    'payment.success.message': 'Thank you! Your payment details have been submitted for verification.',
    'payment.success.confirmation': 'You will receive a confirmation email once your payment is verified by our team.',
    'payment.success.home': 'Go to Home',
    'payment.security.secure': '• 100% secure payments',
    'payment.security.upi': '• UPI payment supported',
    'payment.security.verification': '• Manual verification process',
    'payment.mass.details': 'Mass Booking Details',
    'payment.start.date': 'Start Date',
    'payment.time': 'Time',
    'payment.intention': 'Intention',
    'payment.days': 'Number of Days',
    
    // Donations Page
    'donations.title': 'Make a Donation',
    'donations.subtitle': 'Your heartfelt donations help maintain the shrine, support charitable activities, and advance community services. Every contribution makes a difference in someone\'s life.',
    'donations.details': 'Donation Details',
    'donations.purpose': 'Select donation purpose',
    'donations.purpose.charity': 'Charitable Works',
    'donations.purpose.education': 'Education Fund',
    'donations.purpose.festival': 'Festival Celebration',
    'donations.purpose.general': 'General Donation',
    'donations.purpose.poor': 'Help for the Poor',
    'donations.purpose.renovation': 'Shrine Renovation',
    'donations.amount': 'Select amount',
    'donations.custom': 'Custom Amount',
    'donations.proceed': 'Proceed to Donation',
    'donations.help.title': 'How Your Donation Helps',
    'donations.help.charity': 'Support for charitable activities and community services',
    'donations.help.education': 'Support for educational programs and scholarships',
    'donations.help.festival': 'Support for special festival events and worship',
    'donations.help.general': 'General support for shrine maintenance and all activities',
    'donations.help.renovation': 'Help maintain and improve shrine facilities',
    'donations.tax.title': 'Tax Benefits',
    'donations.tax.description': 'Donations to religious institutions may be eligible for tax benefits under applicable tax laws. Please consult your tax advisor for details.',
    'donations.need.help': 'Need Help?',
    'donations.contact': 'Contact us for questions about donations or payment methods.',
    'donations.features': 'Payment Features',
    'donations.features.secure': '• 100% secure payment',
    'donations.features.upi': '• UPI payment supported',
    'donations.features.verification': '• Manual verification process',
    
    // Gallery Page
    'gallery.title': 'Sacred Gallery',
    'gallery.subtitle': 'Witness the divine moments and sacred memories of our beloved shrine through these blessed captures',
    'gallery.all': 'All',
    'gallery.photos': 'Photos',
    'gallery.videos': 'Videos',
    
    // Live Stream Page
    'livestream.title': 'Live Mass Stream',
    'livestream.subtitle': 'Join us for live streaming of Holy Mass and special ceremonies from Devasahayam Mount Shrine',
    'livestream.live.now': 'LIVE NOW',
    'livestream.watching': 'watching',
    'livestream.special.mass': 'Special Mass',
    'livestream.started': 'Started',
    'livestream.peak': 'Peak',
    'livestream.viewers': 'viewers',
    'livestream.share': 'Share',
    'livestream.chat.youtube': 'Chat on YouTube',
    'livestream.full.features': 'Full Features',
    'livestream.daily.timings': 'Daily Mass Timings',
    'livestream.morning.mass': 'Morning Mass',
    'livestream.evening.mass': 'Evening Mass',
    'livestream.sunday.mass': 'Sunday Mass',
    'livestream.special.events': 'Special Events',
    'livestream.feast.day': 'Feast Day Celebration',
    'livestream.feast.coverage': 'January 14th - Full Day Coverage',
    'livestream.friday.adoration': 'Friday Adoration',
    'livestream.friday.time': 'Every Friday at 7:00 PM',
    'livestream.holy.week': 'Holy Week Services',
    'livestream.extended.coverage': 'Special extended coverage',
    'livestream.youtube.channel': 'Visit Our YouTube Channel',
    'livestream.youtube.subscribe': 'Subscribe to our channel for notifications about upcoming streams and access to recorded masses',
    'livestream.visit.channel': 'Visit YouTube Channel',
    'livestream.important.info': 'Important Information',
    'livestream.info.1': 'Live streaming is available during scheduled mass times',
    'livestream.info.2': 'For full YouTube features (live chat, super chat, reactions), click "Chat on YouTube" or "Full Features"',
    'livestream.info.3': 'Check our YouTube channel for recorded masses if you miss the live stream',
    'livestream.info.4': 'For special ceremonies and feast day celebrations, check our announcements',
    'livestream.info.5': 'You can participate in prayers and responses from wherever you are',
    'livestream.info.6': 'Feel free to leave your prayer intentions in the YouTube live chat',
    'livestream.info.7': 'Use the share button to invite family and friends to join the live mass',
    
    // Livestream Notification
    'livestream.notification.live.now': 'LIVE NOW',
    'livestream.notification.watch.live': 'Watch Live',
    'livestream.notification.starting.soon': 'STARTING SOON',
    'livestream.notification.set.reminder': 'Set Reminder',
    'livestream.notification.watch': 'Watch',
    'livestream.notification.join': 'Join',
    'livestream.notification.soon': 'SOON',
    'livestream.notification.live': 'LIVE',
    'livestream.notification.watching': 'watching',
    'livestream.notification.started': 'Started',
    'livestream.notification.starts.at': 'Starts at',
    
    // Prayer Request Page
    'prayer.request.title': 'Prayer Request',
    'prayer.request.subtitle': 'Share your prayer intentions with us. We will remember you in our daily masses and prayers, seeking the intercession of Saint Devasahayam for your needs.',
    'prayer.request.submit.title': 'Submit Your Prayer Request',
    'prayer.request.name': 'Your Name',
    'prayer.request.email': 'Email Address (Optional)',
    'prayer.request.email.placeholder': 'your.email@example.com',
    'prayer.request.email.note': 'Optional - We\'ll keep you in our prayers',
    'prayer.request.intention': 'Your Prayer Intention',
    'prayer.request.intention.placeholder': 'Share your prayer request... (e.g., for healing, family needs, guidance, thanksgiving)',
    'prayer.request.intention.note': 'Your prayer request will be kept confidential',
    'prayer.request.submit': 'Submit Prayer Request',
    'prayer.request.daily.times': 'Daily Prayer Times',
    'prayer.request.daily.times.subtitle': 'Your intentions will be remembered during:',
    'prayer.request.morning.mass': 'Morning Mass',
    'prayer.request.morning.6am': '6:00 AM',
    'prayer.request.morning.9am': '9:00 AM',
    'prayer.request.evening.mass': 'Evening Mass',
    'prayer.request.evening.6pm': '6:00 PM',
    'prayer.request.saint.prayer.title': 'Prayer to Saint Devasahayam',
    'prayer.request.saint.prayer.1': '"O Saint Devasahayam, faithful witness to Christ, you embraced the Gospel with courage and died for your faith. Intercede for us before God, that we may grow in faith, hope, and love."',
    'prayer.request.saint.prayer.2': '"Help us to be strong in times of trial and to always seek God\'s will in our lives. Through your powerful intercession, may our prayers be heard and our needs be met according to God\'s holy plan. Amen."',
    'prayer.request.gods.promise': 'God\'s Promise',
    'prayer.request.scripture': '"Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened."',
    'prayer.request.scripture.reference': '- Matthew 7:7-8',
    'prayer.request.need.talk': 'Need to Talk?',
    'prayer.request.contact.text': 'If you need spiritual guidance or wish to speak with a priest, please contact us:',
    'prayer.request.phone': '+91 89037 60869',
    'prayer.request.received.title': 'Prayer Request Received',
    'prayer.request.received.message': 'Thank you for sharing your prayer intention with us. Your prayer request will be remembered in our daily masses and prayers at the shrine. May Saint Devasahayam intercede for you and may God bless you abundantly.',
    'prayer.request.received.scripture': '"The prayer of a righteous person is powerful and effective." - James 5:16',
    'prayer.request.received.note': 'Your prayer will be remembered in our daily masses',
    'prayer.request.submit.another': 'Submit Another Request',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Visit us, call us, or reach out for any inquiries. We\'re here to serve you.',
    'contact.address': 'Address',
    'contact.address.full': 'Devasahayam Mount Church, Devasahayam Mount, Aralvaimozhi, Kanyakumari District, Tamil Nadu 629302, India',
    'contact.get.directions': 'Get Directions',
    'contact.phone': 'Phone',
    'contact.phone.number': '+91 89037 60869',
    'contact.phone.available': 'Available: 8:00 AM - 8:00 PM',
    'contact.email': 'Email',
    'contact.email.address': 'devasahayammountshrine@gmail.com',
    'contact.email.response': 'We\'ll respond within 24 hours',
    'contact.office.timings': 'Office & Shrine Timings',
    'contact.monday.saturday': 'Monday - Saturday',
    'contact.monday.saturday.time': '5:00 AM - 9:00 PM',
    'contact.sunday': 'Sunday',
    'contact.sunday.time': '5:00 AM - 10:00 PM',
    'contact.mass.timings': 'Mass Timings:',
    'contact.daily.masses': '6:00 AM, 9:00 AM, 6:00 PM (Daily)',
    'contact.additional.evening': 'Additional evening mass at 7:30 PM',
    'contact.how.to.reach': 'How to Reach Us',
    'contact.by.air': 'By Air',
    'contact.by.air.info': 'Trivandrum International Airport (approximately 50 km). Taxis and buses available from airport',
    'contact.by.train': 'By Train',
    'contact.by.train.info': 'Nagercoil Junction (approximately 15 km). Local transportation readily available',
    'contact.by.road': 'By Road',
    'contact.by.road.info': 'Well-connected by state and private buses. Private vehicles and taxis can easily reach the shrine',
    'contact.connect.with.us': 'Connect With Us',
    'contact.facebook': 'Facebook',
    'contact.youtube': 'YouTube',
    'contact.instagram': 'Instagram',
    
    // Testimonies Page
    'testimonies.title': 'Miracles & Testimonies',
    'testimonies.subtitle': 'Read inspiring stories of faith and answered prayers through Saint Devasahayam.',
    'testimonies.loading': 'Loading testimonies...',
    'testimonies.share.title': 'Share Your Testimony',
    'testimonies.share.button': 'Share Testimony',
    
    // Footer
    'footer.shrine.name': 'Devasahayam Mount Shrine',
    'footer.shrine.description': 'A sacred place of prayer and pilgrimage dedicated to Saint Devasahayam Pillai.',
    'footer.contact.us': 'Contact Us',
    'footer.address': 'Mount Devasahayam, Pilgrimage Road, Tamil Nadu, India',
    'footer.phone': '+91 89037 60869',
    'footer.email': 'info@devasahayammountshrine.com',
    'footer.follow.us': 'Follow Us',
    'footer.copyright': '© 2026 Devasahayam Mount Shrine. All rights reserved.',
    
    // Bus Details Page
    'bus.title': 'Bus Timings – Devasahayam Mount',
    'bus.route.info': 'Bus Route Information',
    'bus.number': 'Bus No:',
    'bus.route': 'Route:',
    'bus.route.path': 'Devasahayam Mount ↔ Nagercoil',
    'bus.travel.time': 'Travel Time:',
    'bus.travel.duration': '45 minutes (one way)',
    'bus.stand.time': 'Stand Time at Nagercoil:',
    'bus.stand.duration': '10 minutes',
    'bus.from.mount': 'From Mount',
    'bus.reach.nagercoil': 'Reach Nagercoil',
    'bus.return.start': 'Return Start',
    'bus.reach.mount.back': 'Reach Mount Back',
    'bus.stay.mount': 'Stay at Mount',
    'bus.notes.title': 'Important Notes',
    'bus.note.weather': 'Bus timings may vary due to weather and traffic conditions',
    'bus.note.festival': 'Additional buses operate during festival days',
    'bus.note.contact': 'For more information, contact +91 89037 60869',
  },
  'தமிழ்': {
    // Hero Section
    'hero.title1': 'துயரங்களின் அன்னை மரியா',
    'hero.title2': 'புனித தேவசகாயம் ஆலயம்',
    'hero.subtitle': 'ஜெபத்திற்கும் தீர்த்த யாத்திரைக்கும் அர்ப்பணிக்கப்பட்ட புனிதத் தலம்',
    
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.about': 'பற்றி',
    'nav.massBooking': 'திருப்பலி பதிவு',
    'nav.donations': 'நன்கொடை',
    'nav.gallery': 'படத்தொகுப்பு',
    'nav.livestream': 'நேரடி ஒளிபரப்பு',
    'nav.testimonies': 'சாட்சியங்கள்',
    'nav.prayerRequest': 'ஜெப வேண்டுகோள்',
    'nav.contact': 'தொடர்பு',
    
    // Buttons
    'button.bookMass': 'திருப்பலி பதிவு செய்ய',
    'button.donate': 'நன்கொடை வழங்க',
    'button.prayerRequest': 'ஜெப வேண்டுகோள்',
    'button.learnMore': 'மேலும் அறிய',
    'button.viewMore': 'மேலும் பார்க்க...',
    
    // About Section
    'about.title': 'புனித தேவசகாயம் அவர்களைப் பற்றி',
    'about.description': 'கத்தோலிக்க திருச்சபையால் புனிதராக அறிவிக்கப்பட்ட முதல் இந்திய சாதாரண விசுவாசியான புனித தேவசகாயம் பிள்ளைக்கு அர்ப்பணிக்கப்பட்ட ஆசீர்வதிக்கப்பட்ட தேவசகாயம் மலை ஆலயத்திற்கு உங்களை அன்புடன் வரவேற்கிறோம்',
    
    // Management Section
    'management.title': 'நிர்வாகம்',
    
    // Announcements Section
    'announcements.title': 'முக்கிய அறிவிப்புகள்',
    'announcements.feast.title': 'வருடாந்திர திருவிழா கொண்டாட்டம்',
    'announcements.feast.content': '2025 ஜனவரி 14 அன்று புனித தேவசகாயம் திருவிழாவின் மகத்தான கொண்டாட்டத்தில் எங்களுடன் இணைந்திடுங்கள். நாள் முழுவதும் சிறப்பு திருப்பலிகள்.',
    
    // Call to Action Cards
    'cta.bookMass.title': 'திருப்பலி பதிவு செய்ய',
    'cta.bookMass.description': 'உங்கள் நோக்கங்களுக்கும் உங்கள் அன்பார்ந்தவர்களுக்காகவும் திருப்பலி பதிவு செய்ய',
    'cta.donation.title': 'நன்கொடை வழங்க',
    'cta.donation.description': 'இந்த ஆலயத்தையும் அதன் தொண்டு பணிகளையும் ஆதரிக்க',
    'cta.prayer.title': 'ஜெப வேண்டுகோள்',
    'cta.prayer.description': 'எங்கள் ஜெபங்களில் நினைவுகூர உங்கள் ஜெப வேண்டுகோளை சமர்ப்பிக்க',
    
    // Common
    'common.language': 'மொழி',
    'common.welcome': 'எங்கள் ஆன்மீக இல்லத்திற்கு வரவேற்கிறோம்',
    
    // About Page
    'about.page.title': 'புனித தேவசகாயம் பிள்ளை',
    'about.page.subtitle': 'இந்தியாவின் முதல் பொதுநிலை புனிதர் | விசுவாசத்தின் இரத்த சாட்சி | 1712 - 1752',
    'about.statue.title': 'புனித தேவசகாயம் பிள்ளையின் திருவுருவச் சிலை',
    'about.life.title': 'நம்பிக்கையும் தைரியமும் நிறைந்த வாழ்க்கை',
    'about.life.description': '1712 ஆம் ஆண்டு செல்வமிக்க இந்து நாயர் குடும்பத்தில் நீலகண்ட பிள்ளையாக பிறந்த தேவசகாயம் பிள்ளை, 2022 மே 15 அன்று திருத்தந்தை பிரான்சிஸ் அவர்களால் இந்தியாவின் முதல் பொதுநிலை புனிதராக அறிவிக்கப்பட்டார்.',
    'about.journey.description': 'அரண்மனை அதிகாரியிலிருந்து கிறிஸ்தவ இரத்த சாட்சியாக மாறிய அவரது பயணம், துன்புறுத்தல்களிடையே அசைக்க முடியாத நம்பிக்கையையும் மரியாதையையும் வெளிப்படுத்துகிறது.',
    'about.early.title': 'ஆரம்ப வாழ்க்கையும் மனமாற்றமும்',
    'about.early.birth': 'நீலகண்ட பிள்ளை 1712 ஏப்ரல் 23 அன்று திருவிதாங்கூர் நாட்டின் நட்டாலம் கிராமத்தில் பிறந்தார்.',
    'about.early.father': 'அவரது தந்தை வாசுதேவன் நம்பூதிரி, திருவட்டாரில் உள்ள ஆதிகேசவ பெருமாள் கோவிலின் பூசாரியாக இருந்தார்.',
    'about.early.palace': 'மகாராஜா மார்த்தாண்ட வர்மாவின் அரண்மனை தொடர்புகள் கொண்ட செல்வாக்குள்ள குடும்பத்தில் வளர்ந்த நீலகண்டன், அரண்மனை சேவையில் சேர்ந்து ராமையன் தளவாவின் கீழ் அதிகாரியாக உயர்ந்தார்.',
    'about.turning.title': 'திருப்புமுனை',
    'about.turning.battle': '1741 ஆம் ஆண்டு கொலச்சல் போருக்குப் பிறகு, டச்சு தளபதி கேப்டன் யூஸ்டாசியஸ் டி லன்னாய் கைது செய்யப்பட்டார்.',
    'about.turning.friendship': 'டி லன்னாயுடன் ஏற்பட்ட நட்பின் மூலம் நீலகண்டன் கிறிஸ்தவ மதத்தில் ஆர்வம் கொண்டார்.',
    'about.turning.baptism': '1745 ஆம் ஆண்டு அவர் "லாசர்" என்ற பெயரில் திருமுழுக்கு பெற்றார்; பின்னர் "தேவசகாயம்" (தேவனின் உதவி) என்ற மலையாளப் பெயரை ஏற்றார்.',
    'about.timeline.title': 'அவரது வாழ்க்கை காலவரிசை',
    'about.timeline.date.birth': '1712 ஏப்ரல் 23',
    'about.timeline.date.battle': '1741',
    'about.timeline.date.conversion': '1745',
    'about.timeline.date.imprisonment': '1749 – 1752',
    'about.timeline.date.martyrdom': '1752 ஜனவரி 14',
    'about.timeline.date.beatified': '2012 டிசம்பர் 2',
    'about.timeline.date.canonized': '2022 மே 15',
    'about.timeline.birth': 'திருவிதாங்கூர் நட்டாலத்தில் நீலகண்ட பிள்ளையாக பிறந்தார்',
    'about.timeline.battle': 'கொலச்சல் போர் – டி லன்னாயுடன் நட்பு',
    'about.timeline.conversion': 'கிறிஸ்தவ மதத்திற்கு மாறி தேவசகாயம் என திருமுழுக்கு பெற்றார்',
    'about.timeline.imprisonment': 'மூன்று ஆண்டுகள் சிறையில் அடைக்கப்பட்டு கொடுமைப்படுத்தப்பட்டார்',
    'about.timeline.martyrdom': 'ஆரல்வாய்மொழியில் இரத்த சாட்சியாக மரணமடைந்தார்',
    'about.timeline.beatified': 'திருத்தந்தை பெனடிக்ட் XVI அவர்களால் பீடுபடுத்தப்பட்டார்',
    'about.timeline.canonized': 'திருத்தந்தை பிரான்சிஸ் அவர்களால் புனிதராக அறிவிக்கப்பட்டார்',
    'about.persecution.title': 'துன்புறுத்தலும் இரத்த சாட்சித்துவமும்',
    'about.persecution.anger': 'தேவசகாயத்தின் கிறிஸ்தவ மனமாற்றம் பிராமண பூசாரிகள், நிலப்பிரபுக்கள் மற்றும் அரச குடும்பத்தினரிடையே கடும் எதிர்ப்பை ஏற்படுத்தியது.',
    'about.persecution.accused': 'பொய்யான குற்றச்சாட்டுகள் சுமத்தப்பட்டு அவர் மூன்று ஆண்டுகள் சிறையில் அடைக்கப்பட்டார்.',
    'about.persecution.faith': 'எவ்வளவு துன்பம் இருந்தாலும் அவரது விசுவாசம் தளரவில்லை.',
    'about.miracle.quote': '"கிறிஸ்துவுக்கான அவரது சாட்சியம் கிறிஸ்துவின் வருகைக்கான கவனத்தின் ஒரு உதாரணம். இந்த புனித காலம் நம் வாழ்க்கையை மீண்டும் ஒருமுறை நமது நம்பிக்கையான கிறிஸ்துவின் மீது மையப்படுத்த உதவட்டும்."',
    'about.quote.attribution': '- திருத்தந்தை பெனடிக்ட் XVI, டிசம்பர் 2, 2012',
    'about.persecution.conversion': 'தேவசகாயத்தின் கிறிஸ்தவ மதமாற்றம் பிராமண குருக்கள், நிலப்பிரபுக்கள் மற்றும் அரச குடும்ப உறுப்பினர்களிடையே கோபத்தை ஏற்படுத்தியது. இந்து மதத்தை விட்டு வெளியேறுவது, குறிப்பாக உயர் நாயர் சாதியைச் சேர்ந்த ஒருவருக்கு கடுமையான குற்றமாக கருதப்பட்டது. அவர் மீது பொய்யான குற்றச்சாட்டுகள் சுமத்தப்பட்டு மூன்று ஆண்டுகள் சிறையில் அடைக்கப்பட்டார்.',
    'about.persecution.captivity': 'அவரது சிறைவாசத்தின் போது, ஐரோப்பிய சக்திகள் அவரது விடுதலைக்காக வேண்டுகோள் விடுத்தன. இறுதியில் அவரை நாடுகடத்த உத்தரவு வழங்கப்பட்டது. எனினும், அசல் உத்தரவு மாற்றப்பட்டு, டச்சு பிரதேசத்திற்கு நாடுகடத்துவதற்கு பதிலாக, அவர் ஆரல்வாய்மொழி எல்லைக்கு அழைத்துச் செல்லப்பட்டு கொடூரமான சித்திரவதைக்கு உட்படுத்தப்பட்டார்.',
    'about.persecution.torture': 'அவரது உடலில் சிவப்பு மற்றும் கருப்பு புள்ளிகள் வரையப்பட்டு, இந்து பாரம்பரியத்தில் மரணத்தின் அடையாளமான எருமை மாட்டின் மீது பின்னோக்கி உட்கார வைக்கப்பட்டார். தினமும் அவருக்கு எண்பது அடிகள் கொடுக்கப்பட்டு, அவரது காயங்களில் மிளகு தேய்க்கப்பட்டு, குடிக்க தேங்கிய நீர் மட்டுமே கொடுக்கப்பட்டது.',
    'about.tomb.cathedral': 'நாகர்கோவில் கோட்டாரில் உள்ள புனித பிரான்சிஸ் சவேரியார் பேராலயத்தில் அமைந்துள்ள புனித தேவசகாயம் பிள்ளையின் கல்லறை ஒரு முக்கிய திருத்தலமாக மாறியுள்ளது. அவரது இரத்த சாட்சியத்திற்குப் பிறகு உள்ளூர் மக்களால் அவரது உடல் மீட்கப்பட்டு இந்த தேவாலயத்திற்கு கொண்டு வரப்பட்டது, அங்கு அவரது மரண எச்சங்கள் பலிபீடத்திற்கு அருகில் அடக்கம் செய்யப்பட்டன.',
    'about.tomb.restoration': '2012 ஆம் ஆண்டு அவரது பேரறிவிப்புக்குப் பிறகு கல்லறை மீட்டமைக்கப்பட்டு அழகுபடுத்தப்பட்டது. ஆண்டுதோறும் ஆயிரக்கணக்கான பக்தர்கள் ஜெபங்களை வழங்கவும் அவரது பரிந்துரையை நாடவும் வருகிறார்கள். அவரது உடைமைகள் வடக்கன்குளத்தில் உள்ள ஒரு தேவாலயத்தில் பாதுகாக்கப்பட்டு, ஒவ்வொரு ஆகஸ்ட் 15 அன்றும் மரியாவின் அசம்ப்ஷன் திருநாளில் வெளிப்படுத்தப்படுகின்றன.',
    'about.pilgrimage.sites': 'முக்கிய திருத்தல யாத்திரை இடங்களில் புலியூர்குறிச்சி, அங்கு பாறையிலிருந்து அதிசயமாக நீர் பொங்கியது, மற்றும் ஆரல்வாய்மொழி, அவரது இரத்த சாட்சியத்தின் இடம் அங்கு இப்போது அவரது தியாகத்தை நினைவுகூரும் ஒரு தேவாலயம் நிற்கிறது.',
    'about.image.memorial': 'தேவசகாயம் பிள்ளையின் நினைவுச்சின்னம்',
    'about.image.memorial2': 'தேவசகாயம் பிள்ளை நினைவுச்சின்னம்',
    'about.image.church': 'இரத்த சாட்சியத்தின் இடத்தில் உள்ள தேவாலயம்',
    'about.sacred.title': 'திருத்தலங்களும் இறுதி தங்குமிடமும்',
    'about.sacred.tomb': 'நாகர்கோவில் கோட்டாரில் உள்ள புனித பிரான்சிஸ் சவேரியார் பேராலயத்தில் அமைந்துள்ள புனித தேவசகாயம் பிள்ளையின் கல்லறை முக்கிய திருத்தலமாக விளங்குகிறது.',
    'about.sacred.visitors': 'ஆண்டுதோறும் ஆயிரக்கணக்கானோர் அவரது பரிந்துரையை நாடி வருகிறார்கள்.',
    'about.journey.sainthood': 'புனிதராக்கும் பயணம்',
    'about.journey.path': 'புனிதராக்கும் பாதை 270 ஆண்டுகளுக்கும் மேலாக நீடித்தது. அவரது இரத்த சாட்சியம் 1756 ஆம் ஆண்டிலேயே வத்திக்கானுக்கு அறிவிக்கப்பட்டது. 1780 ஆம் ஆண்டில் புனிதராக்குவதற்கான மனு சமர்ப்பிக்கப்பட்டது. எனினும், 1984 ஆம் ஆண்டு வரை கோட்டார் மறைமாவட்டத்தின் பொதுநிலை மக்களின் முயற்சியால் தீவிர முயற்சிகள் மீண்டும் தொடங்கப்பட்டன.',
    'about.journey.beatification': '2012 ஆம் ஆண்டில் திருத்தந்தை பெனடிக்ட் XVI அவர்களால் "வணக்கத்திற்குரியவர்" என அங்கீகரிக்கப்பட்டார். 2012 டிசம்பர் 2 அன்று நாகர்கோவிலில் அவர் பேரறிவிப்பு செய்யப்பட்டார். 1,00,000 க்கும் மேற்பட்ட கத்தோலிக்கர்கள் இந்த விழாவில் கலந்துகொண்டனர். இறுதியாக, 2020 பிப்ரவரி 21 அன்று திருத்தந்தை பிரான்சிஸ் அவர்கள் தேவசகாயத்தின் பரிந்துரையால் நடந்த அதிசயத்தை அங்கீகரித்தார், இது 2022 மே 15 அன்று அவரது புனிதராக்கலுக்கு வழி வகுத்தது.',
    'about.journey.process': 'புனிதராக்கும் நடைமுறை 270 ஆண்டுகளுக்கும் மேலாக நீடித்தது.',
    'about.journey.completion': '2022 மே 15 அன்று புனிதர் பட்டம் வழங்கப்பட்டது.',
    'about.historic.achievement': 'வரலாற்று சாதனை:',
    'about.historic.description': 'இந்தியாவில் குருவாகவோ துறவியாகவோ இல்லாமல் புனிதராக அறிவிக்கப்பட்ட முதல் கத்தோலிக்கர் புனித தேவசகாயம் பிள்ளை ஆவார். அவரது திருநாள் ஜனவரி 14 அன்று கொண்டாடப்படுகிறது.',
    'about.patron.saint': 'அவர் இந்தியாவின் மற்றும் உலகம் முழுவதும் துன்புறுத்தப்படும் கிறிஸ்தவர்களின் பாதுகாவலர் புனிதராக வணங்கப்படுகிறார். அவரது வாழ்க்கை சமூக அழுத்தங்கள் மற்றும் துன்புறுத்தல்களுக்கு மத்தியிலும் ஒருவரின் மனசாட்சி மற்றும் விசுவாசத்தைப் பின்பற்றும் தைரியத்தை அடையாளப்படுத்துகிறது. அவரது கதை விசுவாசிகளை கண்ணியம் மற்றும் இரக்கத்துடன் தங்கள் நம்பிக்கைகளில் உறுதியாக நிற்க ஊக்குவிக்கிறது.',
    'about.witness.legacy': 'அவரது மரணத்திற்குப் பிறகு, பல கிறிஸ்தவ யாத்திரிகர்கள் அவரது கல்லறையை பார்வையிட்டு ஜெபங்களை வழங்கியுள்ளனர். கிறிஸ்துவுக்கான அவரது சாட்சியம் மில்லியன் கணக்கான மக்களை தொடர்ந்து ஊக்குவிக்கிறது, விசுவாசத்தில் கவனம் மற்றும் துன்பங்களை எதிர்கொள்ளும் தைரியம் தலைமுறைகளுக்கு நீடித்த மரபை விட்டுச் செல்ல முடியும் என்பதை நிரூபிக்கிறது.',
    'about.legacy.title': 'மரபும் பக்தி வணக்கமும்',
    'about.legacy.symbol': 'புனித தேவசகாயம் பிள்ளை தைரியமும் விசுவாசமும் கொண்ட அடையாளமாக போற்றப்படுகிறார்.',
    'about.legacy.feast': 'அவரது திருநாள் ஜனவரி 14 அன்று கொண்டாடப்படுகிறது.',
    'about.vision.title': 'எங்கள் நோக்கு',
    'about.vision.description': 'புனித தேவசகாயத்தின் வாழ்க்கை மூலம் நம்பிக்கை, நம்புதல் மற்றும் அன்பை ஊக்குவித்தல்.',
    'about.mission.title': 'எங்கள் பணிக்கோள்',
    'about.mission.description': 'ஆன்மீக வளர்ச்சி, வழிபாடு மற்றும் சமூக சேவையை வழங்குதல்.',
    'about.shrine.title': 'எங்கள் திருத்தலம் பற்றி',
    'about.shrine.description': 'தேவசகாயம் மலைத் திருத்தலம் புனித தேவசகாயம் பிள்ளையின் மரபை போற்றுகிறது.',
    'about.shrine.pilgrimage': 'தமிழ்நாட்டின் ஆரல்வாய்மொழியில் அமைந்துள்ள தேவசகாயம் பிள்ளை திருத்தலம், இந்தியாவின் முதல் பொதுநிலை கத்தோலிக்க புனிதரான புனித தேவசகாயம் பிள்ளைக்கு அர்ப்பணிக்கப்பட்ட ஒரு முக்கியமான கிறிஸ்தவ திருத்தலமாகும். வரலாற்று சிறப்புமிக்க ஆரல்வாய்மொழி கணவாய் அருகே அமைந்துள்ள இந்த திருத்தலம், அவரது இரத்த சாட்சியத்துடன் தொடர்புடைய இடத்தைக் குறிக்கிறது மற்றும் அவரது அசைக்க முடியாத விசுவாசம் மற்றும் தியாகத்திற்கு சாட்சியாக நிற்கிறது. ஆண்டு முழுவதும், குறிப்பாக வருடாந்திர திருவிழாவின் போது பக்தர்களை ஈர்க்கும் இந்த திருத்தலம், அனைத்து மத மக்களுக்கும் தைரியம், பக்தி மற்றும் ஆன்மீக உத்வேகத்தின் அடையாளமாக நிற்கிறது.',
    'about.services.title': 'எங்கள் சேவைகள் மற்றும் செயல்பாடுகள்',
    'about.services.masses': 'தினசரி திருப்பலி',
    'about.services.masses.time': 'காலை 6:00, 9:00, மாலை 6:00',
    'about.services.pilgrimage': 'திருத்தல யாத்திரை திட்டங்கள்',
    'about.services.pilgrimage.desc': 'திருத்தல யாத்திரை மற்றும் ஆன்மீக முகாம்கள்',
    'about.services.charity': 'தொண்டு பணிகள்',
    'about.services.charity.desc': 'கல்வி, மருத்துவம் மற்றும் ஏழைகளுக்கான உதவிகள்',
    'about.services.confession': 'பாவமன்னிப்பு மற்றும் ஆலோசனை',
    'about.services.confession.desc': 'பாவமன்னிப்பு மற்றும் ஆன்மிக ஆலோசனை',
    'about.services.feast': 'திருவிழா கொண்டாட்டங்கள்',
    'about.services.feast.desc': 'திருவிழா கொண்டாட்டம் – ஜனவரி 14',
    'about.services.youth': 'இளைஞர் பணிகள்',
    'about.services.youth.desc': 'இளைஞர்களுக்கான விசுவாச மற்றும் சமூக சேவை திட்டங்கள்',
    
    // Mass Booking Page
    'mass.booking.title': 'திருப்பலி முன்பதிவு',
    'mass.booking.subtitle': 'உங்கள் தனிப்பட்ட நோக்கங்கள், உங்கள் அன்புக்குரியவர்கள் அல்லது மறைந்த ஆத்மாக்களின் நினைவாக ஒரு திருப்பலியை அர்ப்பணிக்கலாம். திருப்பலி முன்பதிவு கோரிக்கையை சமர்ப்பிக்க கீழே உள்ள படிவத்தை தயவுசெய்து பூர்த்தி செய்யவும்.',
    'mass.booking.details': 'முன்பதிவு விவரங்கள்',
    'mass.booking.fullName': 'முழு பெயர்',
    'mass.booking.email': 'மின்னஞ்சல் முகவரி',
    'mass.booking.phone': 'தொலைபேசி எண்',
    'mass.booking.date': 'விரும்பிய தேதி',
    'mass.booking.time': 'விரும்பிய நேரம்',
    'mass.booking.intentionType': 'திருப்பலி நோக்கம்',
    'mass.booking.intentionDetails': 'திருப்பலி நோக்கத்தின் விவரங்கள்',
    'mass.booking.numberOfDays': 'நாட்களின் எண்ணிக்கை',
    'mass.booking.numberOfDaysDesc': 'தேர்ந்தெடுத்த தேதியிலிருந்து தொடர்ந்து பல நாட்களுக்கு ஒரே நோக்கத்திற்காக திருப்பலியை முன்பதிவு செய்யலாம்.',
    'mass.booking.submit': 'முன்பதிவு கோரிக்கையை சமர்ப்பிக்கவும்',
    'mass.booking.amount': 'திருப்பலி முன்பதிவு கட்டணம்',
    'mass.booking.pricePerMass': 'ஒரு திருப்பலிக்கான கட்டணம்: ₹150',
    'mass.booking.paymentInstructions': 'அனுமதி கிடைத்த பிறகு கட்டண விவரங்கள் அனுப்பப்படும்',
    'mass.booking.importantNotes': 'முக்கிய குறிப்புகள்',
    'mass.booking.note1': '• திருப்பலி முன்பதிவு கிடைப்புக்கு உட்பட்டது',
    'mass.booking.note2': '• உறுதிப்படுத்தல் மின்னஞ்சல் மூலம் அனுப்பப்படும்',
    'mass.booking.note3': '• திருப்பலி தொடங்குவதற்கு 15 நிமிடங்களுக்கு முன் வருகை தரவும்',
    'mass.booking.note4': '• சிறப்பு ஏற்பாடுகளுக்கு எங்களை தொடர்புகொள்ளவும்',
    'mass.booking.thanksgiving': 'நன்றி தெரிவிப்பு',
    'mass.booking.petition': 'வேண்டுதல்',
    'mass.booking.memorial': 'நினைவு',
    'mass.booking.placeholder.thanksgiving': 'நன்றி தெரிவிப்பு நோக்கத்தின் விவரங்களை உள்ளிடவும்',
    'mass.booking.placeholder.petition': 'வேண்டுதல் கோரிக்கையின் விவரங்களை உள்ளிடவும்',
    'mass.booking.placeholder.memorial': 'நினைவு விவரங்களை உள்ளிடவும் (நபரின் பெயர், போன்றவை)',
    'mass.booking.placeholder.default': 'திருப்பலி நோக்கத்தின் விவரங்களை உள்ளிடவும்',
    'mass.timings.title': 'திருப்பலி நேரங்கள்',
    'mass.timings.daily': 'தினசரி திருப்பலி',
    'mass.timings.monday.thursday': 'திங்கள் – வியாழன்',
    'mass.timings.morning': 'காலை: 6:00 மணி',
    'mass.timings.evening': 'மாலை: 6:30 மணி',
    'mass.timings.friday': 'வெள்ளிக்கிழமை திருப்பலி',
    'mass.timings.friday.morning1': 'காலை: 6:00 மணி திருப்பலி',
    'mass.timings.friday.morning2': 'காலை: 10:30 மணி நவீனா திருப்பலி',
    'mass.timings.friday.morning3': 'காலை: 11:00 மணி நவீனா திருப்பலி',
    'mass.timings.friday.evening': 'மாலை: 6:30 மணி திருப்பலி',
    'mass.timings.friday.night': 'இரவு: 8:00 மணி, 9:00 மணி',
    'mass.timings.saturday': 'சனிக்கிழமை திருப்பலி',
    'mass.timings.saturday.morning1': 'காலை: 6:00 மணி திருப்பலி',
    'mass.timings.saturday.morning2': 'காலை: 11:30 மணி நவீனா திருப்பலி',
    'mass.timings.saturday.evening': 'மாலை: 6:30 மணி திருப்பலி',
    'mass.timings.saturday.night': 'இரவு: 8:00 மணி, 9:00 மணி',
    'mass.timings.sunday': 'ஞாயிற்றுக்கிழமை திருப்பலி',
    'mass.timings.sunday.morning1': 'காலை: 7:00 மணி திருப்பலி',
    'mass.timings.sunday.morning2': 'காலை: 7:00 மணி திருப்பலி',
    'mass.timings.sunday.afternoon': 'மதியம்: 12:00 மணி (புனித யாத்திரிகர்களுக்காக)',
    'mass.timings.sunday.evening': 'மாலை: 6:30 மணி திருப்பலி',
    'mass.timings.sunday.night': 'இரவு: 8:00 மணி, 9:00 மணி',
    'mass.timings.novena1': '• நவீனா – தேவசகாயம் அனுக்குஞ்சு',
    'mass.timings.novena2': '• திருவாசல் வணக்கம்',
    'mass.timings.novena3': '• திருஞானசம்பந்தர் வணக்கம்',
    'mass.timings.special': 'சிறப்பு நாட்கள்',
    'mass.timings.special.desc': 'மாதம் தோறும் குறிப்பிட்ட தேதிகளில் திருத்தலத்தில் சிறப்பு வழிபாடுகள் நடைபெறுகின்றன. அனைத்து பக்தர்களும் பங்கேற்கும் வாய்ப்பு வழங்கப்படுகிறது.',
    'mass.timings.special.15th': '• ஒவ்வொரு மாதமும் 15ஆம் தேதி – மாலை 7:00 மணிக்கு பாதுகாவலர் திருப்பலி',
    'mass.timings.special.14th': '• ஒவ்வொரு மாதமும் 14ஆம் தேதி – மாதா மகிமை, மாலை 6:00 மணி திருப்பலி',
    'mass.timings.special.tuesday': '• முதல் செவ்வாய்க்கிழமை – புனித அந்தோனியார் வழிபாடு',
    'mass.timings.special.wednesday': '• முதல் புதன்கிழமை – எங்கள் திருச்சபை வழிபாடு',
    'mass.timings.special.friday': '• முதல் வெள்ளிக்கிழமை – இயேசு சதுக்க வழிபாடு',
    'mass.timings.special.saturday1': '• முதல் சனிக்கிழமை – தேவசகாயம் பாதுகாவலர் விழா',
    'mass.timings.special.saturday2': '• முதல் சனிக்கிழமை – மாலை 7:00 மணிக்கு, புனித பாப்பரால் ஆசீர்வதிக்கப்பட்ட அவர் லேடி ஆஃப் சோரோஸ் திருவுருவம் ஊர்வலமாக கொண்டு செல்லப்படும் திருப்பலி',
    
    // Payment Confirmation
    'payment.confirmation.required': 'கட்டண உறுதிப்படுத்தல் தேவை',
    'payment.utr.number': '12 இலக்க UTR எண்ணை உள்ளிடவும்',
    'payment.utr.description': 'இந்த எண்ணை உங்கள் கட்டண செயலியின் பரிவர்த்தனை வரலாற்றில் காணலாம்',
    'payment.screenshot.upload': 'திரைபிடிப்பு (Screenshot) பதிவேற்றவும்',
    'payment.screenshot.click': 'கிளிக் செய்து திரைபிடிப்பை பதிவேற்றவும்',
    'payment.screenshot.format': 'PNG, JPG வடிவங்கள் – அதிகபட்சம் 5MB வரை',
    'payment.submit.details': 'கட்டண விவரங்களை சமர்ப்பிக்கவும்',
    'payment.summary': 'கட்டண சுருக்கம்',
    'payment.complete': 'உங்கள் கட்டணத்தை நிறைவு செய்யவும்',
    'payment.qr.scan': 'QR குறியீட்டை ஸ்கேன் செய்து கட்டணம் செலுத்தவும்',
    'payment.qr.description': 'Google Pay, PhonePe, Paytm போன்ற எந்த UPI செயலியையும் பயன்படுத்தி ஸ்கேன் செய்யலாம்',
    'payment.amount': 'செலுத்த வேண்டிய தொகை',
    'payment.made': 'நான் கட்டணத்தை செலுத்திவிட்டேன்',
    'payment.utr.label': 'UTR எண் / பரிவர்த்தனை அடையாள எண்',
    'payment.utr.placeholder': '12 இலக்க UTR எண்ணை உள்ளிடவும்',
    'payment.utr.help': 'இந்த எண்ணை உங்கள் கட்டண செயலியின் பரிவர்த்தனை வரலாற்றில் காணலாம்',
    'payment.screenshot.label': 'கட்டண திரைபிடிப்பு',
    'payment.screenshot.formats': 'PNG, JPG வடிவங்கள் – அதிகபட்சம் 5MB வரை',
    'payment.submitting': 'சமர்ப்பிக்கிறது...',
    'payment.success.title': 'கட்டண விவரங்கள் சமர்ப்பிக்கப்பட்டன',
    'payment.success.message': 'நன்றி! உங்கள் கட்டண விவரங்கள் சரிபார்ப்புக்காக சமர்ப்பிக்கப்பட்டுள்ளன.',
    'payment.success.confirmation': 'எங்கள் குழுவினர் உங்கள் கட்டணத்தை சரிபார்த்த பிறகு உறுதிப்படுத்தல் மின்னஞ்சல் அனுப்பப்படும்.',
    'payment.success.home': 'முகப்புக்கு செல்லவும்',
    'payment.security.secure': '• 100% பாதுகாப்பான கட்டண முறை',
    'payment.security.upi': '• UPI கட்டணம் ஆதரிக்கப்படுகிறது',
    'payment.security.verification': '• கைமுறை சரிபார்ப்பு நடைமுறை உள்ளது',
    'payment.mass.details': 'திருப்பலி முன்பதிவு விவரங்கள்',
    'payment.start.date': 'தொடக்க தேதி',
    'payment.time': 'நேரம்',
    'payment.intention': 'நோக்கம்',
    'payment.days': 'நாட்களின் எண்ணிக்கை',
    
    // Donations Page
    'donations.title': 'நன்கொடை வழங்குங்கள்',
    'donations.subtitle': 'உங்கள் மனமார்ந்த நன்கொடைகள் திருத்தலத்தை பராமரிக்க, தொண்டு நடவடிக்கைகளை ஆதரிக்க, மற்றும் சமூக சேவைகளை முன்னெடுக்க உதவுகின்றன. ஒவ்வொரு பங்களிப்பும் ஒருவரின் வாழ்க்கையில் மாற்றத்தை ஏற்படுத்துகிறது.',
    'donations.details': 'நன்கொடை விவரங்கள்',
    'donations.purpose': 'நன்கொடை நோக்கத்தை தேர்வு செய்யவும்',
    'donations.purpose.charity': 'தொண்டு பணிகள்',
    'donations.purpose.education': 'கல்வி நிதி',
    'donations.purpose.festival': 'திருவிழா கொண்டாட்டம்',
    'donations.purpose.general': 'பொது நன்கொடை',
    'donations.purpose.poor': 'ஏழைகள் உதவி',
    'donations.purpose.renovation': 'திருத்தல மறுசீரமைப்பு',
    'donations.amount': 'தொகையை தேர்வு செய்யவும்',
    'donations.custom': 'தனிப்பட்ட தொகை',
    'donations.proceed': 'நன்கொடை செலுத்த தொடரவும்',
    'donations.help.title': 'உங்கள் நன்கொடை எவ்வாறு உதவுகிறது',
    'donations.help.charity': 'தொண்டு நடவடிக்கைகள் மற்றும் சமூக சேவைகளுக்கான ஆதரவு',
    'donations.help.education': 'கல்வி திட்டங்கள் மற்றும் உதவித்தொகைகளுக்கான ஆதரவு',
    'donations.help.festival': 'சிறப்பு திருவிழா நிகழ்ச்சிகள் மற்றும் வழிபாடுகளுக்கான ஆதரவு',
    'donations.help.general': 'திருத்தல பராமரிப்பு மற்றும் அனைத்து செயல்பாடுகளுக்கும் பொதுவான ஆதரவு',
    'donations.help.renovation': 'திருத்தல வசதிகளை பராமரிக்கவும் மேம்படுத்தவும் உதவுங்கள்',
    'donations.tax.title': 'வரி சலுகைகள்',
    'donations.tax.description': 'மத நிறுவனங்களுக்கு வழங்கப்படும் நன்கொடைகள் நடைமுறையில் உள்ள வரி சட்டங்களின் படி வரி சலுகைக்கு தகுதியானதாக இருக்கலாம். விவரங்களுக்கு உங்கள் வரி ஆலோசகரை அணுகவும்.',
    'donations.need.help': 'உதவி தேவையா?',
    'donations.contact': 'நன்கொடை அல்லது கட்டண முறைகள் தொடர்பான கேள்விகளுக்கு எங்களை தொடர்புகொள்ளவும்.',
    'donations.features': 'கட்டண அம்சங்கள்',
    'donations.features.secure': '• 100% பாதுகாப்பான கட்டணம்',
    'donations.features.upi': '• UPI கட்டணம் ஆதரிக்கப்படுகிறது',
    'donations.features.verification': '• கைமுறை சரிபார்ப்பு நடைமுறை',
    
    // Gallery Page
    'gallery.title': 'புனிதக் காட்சியகம்',
    'gallery.subtitle': 'இந்த ஆசீர்வதிக்கப்பட்ட காட்சிகளின் மூலம் எங்கள் அன்பான திருத்தலத்தின் தெய்வீக தருணங்களையும் புனித நினைவுகளையும் காணுங்கள்',
    'gallery.all': 'அனைத்தும்',
    'gallery.photos': 'புகைப்படங்கள்',
    'gallery.videos': 'காணொளிகள்',
    
    // Live Stream Page
    'livestream.title': 'நேரடி திருப்பலி ஒளிபரப்பு',
    'livestream.subtitle': 'தேவசகாயம் மலைத் திருத்தலத்திலிருந்து நேரடி திருப்பலி மற்றும் சிறப்பு வழிபாடுகளின் ஒளிபரப்பில் எங்களுடன் இணைந்திடுங்கள்',
    'livestream.live.now': 'தற்போது நேரலையில்',
    'livestream.watching': 'பேர் பார்க்கின்றனர்',
    'livestream.special.mass': 'சிறப்பு திருப்பலி',
    'livestream.started': 'தொடங்கிய நேரம்',
    'livestream.peak': 'அதிகபட்ச பார்வையாளர்கள்:',
    'livestream.viewers': 'பார்வையாளர்கள்',
    'livestream.share': 'பகிரவும்',
    'livestream.chat.youtube': 'யூடியூபில் உரையாடல்',
    'livestream.full.features': 'முழு அம்சங்கள்',
    'livestream.daily.timings': 'தினசரி திருப்பலி நேரங்கள்',
    'livestream.morning.mass': 'காலை திருப்பலி',
    'livestream.morning.time': 'காலை 6:00 மணி',
    'livestream.evening.mass': 'மாலை திருப்பலி',
    'livestream.evening.time': 'மாலை 6:30 மணி',
    'livestream.sunday.mass': 'ஞாயிறு திருப்பலி',
    'livestream.sunday.time': 'காலை 9:00 மணி',
    'livestream.special.events': 'சிறப்பு நிகழ்வுகள்',
    'livestream.feast.day': 'திருவிழா கொண்டாட்டம்',
    'livestream.feast.coverage': 'ஜனவரி 14 – முழு நாள் ஒளிபரப்பு',
    'livestream.friday.adoration': 'வெள்ளிக்கிழமை ஆராதனை',
    'livestream.friday.time': 'ஒவ்வொரு வெள்ளிக்கிழமையும் மாலை 7:00 மணிக்கு',
    'livestream.holy.week': 'புனித வார வழிபாடுகள்',
    'livestream.extended.coverage': 'சிறப்பு நீட்டிக்கப்பட்ட ஒளிபரப்பு',
    'livestream.youtube.channel': 'எங்கள் யூடியூப் சேனலைப் பார்வையிடுங்கள்',
    'livestream.youtube.subscribe': 'வரவிருக்கும் நேரலைகள் குறித்த அறிவிப்புகள் மற்றும் பதிவுசெய்யப்பட்ட திருப்பலிகளைப் பெற எங்கள் சேனலை சந்தா செய்யுங்கள்',
    'livestream.visit.channel': 'யூடியூப் சேனலைப் பார்வையிடுங்கள்',
    'livestream.important.info': 'முக்கிய தகவல்கள்',
    'livestream.info.1': 'நிர்ணயிக்கப்பட்ட திருப்பலி நேரங்களில் மட்டுமே நேரடி ஒளிபரப்பு கிடைக்கும்',
    'livestream.info.2': 'யூடியூபின் முழு அம்சங்களை (நேரடி உரையாடல், சூப்பர் சாட், எதிர்வினைகள்) பயன்படுத்த "யூடியூபில் உரையாடல்" அல்லது "முழு அம்சங்கள்" என்பவற்றை கிளிக் செய்யவும்',
    'livestream.info.3': 'நேரலை தவறினால் பதிவுசெய்யப்பட்ட திருப்பலிகளுக்காக எங்கள் யூடியூப் சேனலைப் பார்வையிடுங்கள்',
    'livestream.info.4': 'சிறப்பு சடங்குகள் மற்றும் திருவிழா கொண்டாட்டங்களுக்கு எங்கள் அறிவிப்புகளைப் பார்க்கவும்',
    'livestream.info.5': 'நீங்கள் எங்கு இருந்தாலும் ஜெபங்களிலும் பதில்களிலும் பங்கேற்கலாம்',
    'livestream.info.6': 'உங்கள் ஜெப நோக்கங்களை யூடியூப் நேரடி உரையாடலில் பதிவு செய்யலாம்',
    'livestream.info.7': 'குடும்பத்தினரையும் நண்பர்களையும் நேரடி திருப்பலியில் இணைக்க பகிர்வு பொத்தானைப் பயன்படுத்துங்கள்',
    
    // Livestream Notification
    'livestream.notification.live.now': 'நேரலை நடைபெற்று வருகிறது',
    'livestream.notification.watch.live': 'நேரலையாக பாருங்கள்',
    'livestream.notification.starting.soon': 'விரைவில் தொடங்குகிறது',
    'livestream.notification.set.reminder': 'நினைவூட்டல் அமைக்கவும்',
    'livestream.notification.watch': 'பார்க்கவும்',
    'livestream.notification.join': 'இணையுங்கள்',
    'livestream.notification.soon': 'விரைவில்',
    'livestream.notification.live': 'நேரலை',
    'livestream.notification.watching': 'பேர் பார்த்துக் கொண்டிருக்கின்றனர்',
    'livestream.notification.started': 'தொடங்கியது – பிற்பகல்',
    'livestream.notification.starts.at': 'தொடங்கும் நேரம்',
    
    // Prayer Request Page
    'prayer.request.title': 'பிரார்த்தனை வேண்டுகோள்',
    'prayer.request.subtitle': 'உங்கள் பிரார்த்தனை நோக்கங்களை எங்களுடன் பகிர்ந்து கொள்ளுங்கள். உங்கள் தேவைகளுக்காக புனித தேவசகாயரின் பரிந்துரையை நாடி, எங்களின் தினசரி திருப்பலிகள் மற்றும் ஜெபங்களில் நாங்கள் உங்களை நினைவுகூருவோம்.',
    'prayer.request.submit.title': 'உங்கள் பிரார்த்தனை வேண்டுகோளைச் சமர்ப்பிக்கவும்',
    'prayer.request.name': 'உங்கள் பெயரை உள்ளிடவும்',
    'prayer.request.email': 'மின்னஞ்சல் முகவரி (விரும்பினால்)',
    'prayer.request.email.placeholder': 'your.email@example.com',
    'prayer.request.email.note': 'விரும்பினால் - நாங்கள் உங்களுக்காக ஜெபிப்போம்',
    'prayer.request.intention': 'உங்கள் பிரார்த்தனை நோக்கம்',
    'prayer.request.intention.placeholder': 'உங்கள் பிரார்த்தனை வேண்டுகோளைப் பகிரவும்... (உதாரணமாக, குணமடைதல், குடும்பத் தேவைகள், வழிகாட்டுதல், நன்றி தெரிவித்தல்)',
    'prayer.request.intention.note': 'உங்கள் பிரார்த்தனை வேண்டுகோள் இரகசியமாக வைக்கப்படும்',
    'prayer.request.submit': 'வேண்டுகோள் சமர்ப்பிக்கவும்',
    'prayer.request.daily.times': 'தினசரி பிரார்த்தனை நேரங்கள்',
    'prayer.request.daily.times.subtitle': 'உங்கள் நோக்கங்கள் பின்வரும் நேரங்களில் நினைவுகூரப்படும்:',
    'prayer.request.morning.mass': 'காலைத் திருப்பலி',
    'prayer.request.morning.6am': 'காலை 6:00 மணி',
    'prayer.request.morning.9am': 'காலை 9:00 மணி',
    'prayer.request.evening.mass': 'மாலைத் திருப்பலி',
    'prayer.request.evening.6pm': 'மாலை 6:00 மணி',
    'prayer.request.saint.prayer.title': 'புனித தேவசகாயரிடம் பிரார்த்தனை',
    'prayer.request.saint.prayer.1': '"ஓ புனித தேவசகாயரே, கிறிஸ்துவின் உண்மையுள்ள சாட்சியே, நீங்கள் நற்செய்தியைத் துணிச்சலுடன் ஏற்றுக்கொண்டு, உங்கள் விசுவாசத்திற்காக மரித்தீர்கள். நாங்கள் விசுவாசம், நம்பிக்கை மற்றும் அன்பில் வளர, கடவுளுக்கு முன்பாக எங்களுக்காகப் பரிந்து பேசுங்கள்."',
    'prayer.request.saint.prayer.2': '"சோதனையான காலங்களில் நாங்கள் வலிமையாக இருக்கவும், எங்கள் வாழ்வில் எப்போதும் கடவுளின் சித்தத்தைத் தேடவும் எங்களுக்கு உதவுங்கள். உங்கள் சக்திவாய்ந்த பரிந்துரையின் மூலம், எங்கள் ஜெபங்கள் கேட்கப்படவும், கடவுளின் புனித திட்டத்தின்படி எங்கள் தேவைகள் பூர்த்தி செய்யப்படவும் செய்வீராக. ஆமென்."',
    'prayer.request.gods.promise': 'கடவுளின் வாக்குறுதி',
    'prayer.request.scripture': '"கேளுங்கள், அது உங்களுக்குக் கொடுக்கப்படும்; தேடுங்கள், நீங்கள் கண்டடைவீர்கள்; தட்டுங்கள், கதவு உங்களுக்குத் திறக்கப்படும். ஏனெனில் கேட்கிற எவரும் பெற்றுக்கொள்கிறார்; தேடுகிறவர் கண்டடைகிறார்; தட்டுகிறவனுக்குக் கதவு திறக்கப்படும்."',
    'prayer.request.scripture.reference': '- மத்தேயு 7:7-8',
    'prayer.request.need.talk': 'பேச வேண்டுமா?',
    'prayer.request.contact.text': 'உங்களுக்கு ஆன்மீக வழிகாட்டுதல் தேவைப்பட்டாலோ அல்லது ஒரு குருவிடம் பேச விரும்பினாலோ, எங்களைத் தொடர்பு கொள்ளவும்:',
    'prayer.request.phone': '+91 89037 60869',
    'prayer.request.received.title': 'பிரார்த்தனை வேண்டுகோள் பெறப்பட்டது',
    'prayer.request.received.message': 'உங்கள் பிரார்த்தனை நோக்கத்தை எங்களுடன் பகிர்ந்துகொண்டதற்கு நன்றி. உங்கள் பிரார்த்தனை வேண்டுகோள் ஆலயத்தில் நடைபெறும் எங்கள் தினசரி திருப்பலிகள் மற்றும் ஜெபங்களில் நினைவுகூரப்படும். புனித தேவசகாயர் உங்களுக்காகப் பரிந்து பேசட்டும், கடவுள் உங்களை நிறைவாக ஆசீர்வதிக்கட்டும்.',
    'prayer.request.received.scripture': '"நீதிமானுடைய ஜெபம் வல்லமை வாய்ந்தது மற்றும் பயனுள்ளது." - யாக்கோபு 5:16',
    'prayer.request.received.note': 'உங்கள் பிரார்த்தனை எங்கள் தினசரி திருப்பலிகளில் நினைவுகூரப்படும்',
    'prayer.request.submit.another': 'மற்றொரு வேண்டுகோளைச் சமர்ப்பிக்கவும்',
    
    // Contact Page
    'contact.title': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'contact.subtitle': 'வருகை தருங்கள், அழைக்கவும் அல்லது எந்தவொரு விசாரணைக்கும் எங்களை அணுகுங்கள். உங்களுக்கு சேவை செய்வதற்காக நாங்கள் இங்கே உள்ளோம்.',
    'contact.address': 'முகவரி',
    'contact.address.full': 'தேவசகாயம் மலை திருத்தலம், தேவசகாயம் மலை, ஆரல்வாய்மொழி, கன்னியாகுமரி மாவட்டம், தமிழ்நாடு 629302, இந்தியா',
    'contact.get.directions': 'வழிகாட்டி பெறுங்கள்',
    'contact.phone': 'தொலைபேசி',
    'contact.phone.number': '+91 89037 60869',
    'contact.phone.available': 'கிடைக்கும் நேரம்: காலை 8:00 மணி – இரவு 8:00 மணி',
    'contact.email': 'மின்னஞ்சல்',
    'contact.email.address': 'devasahayammountshrine@gmail.com',
    'contact.email.response': '24 மணி நேரத்திற்குள் பதிலளிப்போம்',
    'contact.office.timings': 'அலுவலகம் & திருத்தல நேரங்கள்',
    'contact.monday.saturday': 'திங்கள் – சனி',
    'contact.monday.saturday.time': 'காலை 5:00 மணி – இரவு 9:00 மணி',
    'contact.sunday': 'ஞாயிறு',
    'contact.sunday.time': 'காலை 5:00 மணி – இரவு 10:00 மணி',
    'contact.mass.timings': 'திருப்பலி நேரங்கள்:',
    'contact.daily.masses': 'தினசரி: காலை 6:00 மணி, காலை 9:00 மணி, மாலை 6:00 மணி',
    'contact.additional.evening': 'கூடுதல் மாலை திருப்பலி மாலை 7:30 மணிக்கு',
    'contact.how.to.reach': 'எங்களை அடையும் வழிகள்',
    'contact.by.air': 'விமானம் மூலம்',
    'contact.by.air.info': 'திருவனந்தபுரம் சர்வதேச விமான நிலையம் (சுமார் 50 கி.மீ). விமான நிலையத்திலிருந்து டாக்ஸி மற்றும் பேருந்து வசதிகள் உள்ளன',
    'contact.by.train': 'ரயில் மூலம்',
    'contact.by.train.info': 'நாகர்கோவில் சந்திப்பு நிலையம் (சுமார் 15 கி.மீ). உள்ளூர் போக்குவரத்து வசதிகள் எளிதில் கிடைக்கும்',
    'contact.by.road': 'சாலை மூலம்',
    'contact.by.road.info': 'மாநில மற்றும் தனியார் பேருந்துகள் மூலம் சிறப்பாக இணைக்கப்பட்டுள்ளது. தனியார் வாகனங்கள் மற்றும் டாக்ஸிகள் மூலம் திருத்தலத்தை எளிதில் அடையலாம்',
    'contact.connect.with.us': 'எங்களுடன் இணைந்திருங்கள்',
    'contact.facebook': 'பேஸ்புக்',
    'contact.youtube': 'யூடியூப்',
    'contact.instagram': 'இன்ஸ்டாகிராம்',
    
    // Testimonies Page
    'testimonies.title': 'அதிசயங்கள் & சாட்சியங்கள்',
    'testimonies.subtitle': 'புனித தேவசகாயம் வழியாக விசுவாசத்தாலும் இறைவேண்டுதல்களாலும் கிடைத்த பதில்களை விவரிக்கும் ஊக்கமளிக்கும் அனுபவக் கதைகளை வாசியுங்கள்.',
    'testimonies.loading': 'சாட்சியங்கள் ஏற்றப்படுகின்றன...',
    'testimonies.share.title': 'உங்கள் சாட்சியத்தைப் பகிருங்கள்',
    'testimonies.share.button': 'சாட்சியம் பகிர',
    
    // Footer
    'footer.shrine.name': 'தேவசகாயம் மலை திருத்தலம்',
    'footer.shrine.description': 'புனித தேவசகாயம் பிள்ளை அவர்களுக்கு அர்ப்பணிக்கப்பட்ட பிரார்த்தனை மற்றும் யாத்திரைக்கான புனித திருத்தலம்.',
    'footer.contact.us': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'footer.address': 'தேவசகாயம் மலை, யாத்திரைச் சாலை, தமிழ்நாடு, இந்தியா',
    'footer.phone': '+91 89037 60869',
    'footer.email': 'info@devasahayammountshrine.com',
    'footer.follow.us': 'எங்களைப் பின்தொடருங்கள்',
    'footer.copyright': '© 2026 தேவசகாயம் மலை திருத்தலம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    
    // Bus Details Page
    'bus.title': 'பேருந்து நேரங்கள் – தேவசகாயம் மலை',
    'bus.route.info': 'பேருந்து வழித்தட விவரம்',
    'bus.number': 'பேருந்து எண்:',
    'bus.route': 'வழித்தடம்:',
    'bus.route.path': 'தேவசகாயம் மலை ↔ நாகர்கோவில்',
    'bus.travel.time': 'பயண நேரம்:',
    'bus.travel.duration': '45 நிமிடங்கள் (ஒரு வழி)',
    'bus.stand.time': 'நாகர்கோவில் நிறுத்த நேரம்:',
    'bus.stand.duration': '10 நிமிடங்கள்',
    'bus.from.mount': 'மலையிலிருந்து',
    'bus.reach.nagercoil': 'நாகர்கோவில் அடையும்',
    'bus.return.start': 'திரும்பும் நேரம்',
    'bus.reach.mount.back': 'மீண்டும் மலை அடையும்',
    'bus.stay.mount': 'மலையிலேயே நிறுத்தம்',
    'bus.notes.title': 'முக்கிய குறிப்புகள்',
    'bus.note.weather': 'வானிலை மற்றும் போக்குவரத்து காரணங்களால் பேருந்து நேரங்களில் மாற்றம் இருக்கலாம்',
    'bus.note.festival': 'திருவிழா நாட்களில் கூடுதல் பேருந்துகள் இயக்கப்படும்',
    'bus.note.contact': 'கூடுதல் தகவல்களுக்கு தொடர்பு கொள்ளவும்: +91 89037 60869',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to 'ENG'
    const savedLanguage = localStorage.getItem('shrine-language');
    return (savedLanguage as Language) || 'ENG';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    // Save language to localStorage
    localStorage.setItem('shrine-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};